/** Full navbar inventory from bmwengines.uk URL master list. */

export const navMenus = [
  {
    id: "models",
    label: "MODELS",
    kind: "models",
    groups: [
      {
        title: "Saloons & Tourers",
        items: [
          { label: "1 Series", href: "/1-series", variants: 17, generations: 8 },
          { label: "2 Series", href: "/2-series", variants: 12, generations: 9 },
          { label: "3 Series", href: "/3-series", variants: 29, generations: 13 },
          { label: "4 Series", href: "/4-series", variants: 13, generations: 6 },
          { label: "5 Series", href: "/5-series", variants: 24, generations: 13 },
          { label: "6 Series", href: "/6-series", variants: 9, generations: 7 },
          { label: "7 Series", href: "/7-series", variants: 15, generations: 4 },
          { label: "8 Series", href: "/8-series", variants: 6, generations: 4 },
        ],
      },
      {
        title: "SUV (X)",
        items: [
          { label: "X1", href: "/x1", variants: 11, generations: 3 },
          { label: "X2", href: "/x2", variants: 6, generations: 2 },
          { label: "X3", href: "/x3", variants: 14, generations: 4 },
          { label: "X4", href: "/x4", variants: 6, generations: 2 },
          { label: "X5", href: "/x5", variants: 17, generations: 4 },
          { label: "X6", href: "/x6", variants: 7, generations: 3 },
          { label: "X7", href: "/x7", variants: 5, generations: 1 },
        ],
      },
      {
        title: "M Performance",
        items: [
          { label: "M1", href: "/m1", variants: 1, generations: 1 },
          { label: "M2", href: "/m2", variants: 0, generations: 2 },
          { label: "M3", href: "/m3", variants: 2, generations: 4 },
          { label: "M4", href: "/m4", variants: 2, generations: 0 },
          { label: "M5", href: "/m5", variants: 2, generations: 5 },
          { label: "M6", href: "/m6", variants: 2, generations: 1 },
          { label: "M8", href: "/m8", variants: 1, generations: 0 },
        ],
      },
      {
        title: "Other",
        items: [
          { label: "Z Series", href: "/z-series", variants: 23, generations: 8 },
          { label: "2002", href: "/2002", variants: 1, generations: 0 },
          { label: "i Series", href: "/i-series-electric-motors", variants: 0, generations: 0 },
          { label: "XM", href: "/xm", variants: 0, generations: 0 },
        ],
      },
    ],
  },
  {
    id: "engines",
    label: "ENGINES",
    kind: "columns",
    groups: [
      {
        title: "Modern (B-series)",
        links: [
          { label: "B37/B47", href: "/engine/b37-b47" },
          { label: "B38/B48", href: "/engine/b38-b48" },
          { label: "B47", href: "/engine/b47" },
          { label: "B57/B58", href: "/engine/b57-b58" },
          { label: "B58", href: "/engine/b58" },
        ],
      },
      {
        title: "N-series",
        links: [
          { label: "N13/N20", href: "/engine/n13-n20" },
          { label: "N20", href: "/engine/n20" },
          { label: "N40/N42/N43/N45/N46", href: "/engine/n40-n42-n43-n45-n46" },
          { label: "N47", href: "/engine/n47" },
          { label: "N52/N53", href: "/engine/n52-n53" },
          { label: "N54", href: "/engine/n54" },
          { label: "N54/N55", href: "/engine/n54-n55" },
          { label: "N55", href: "/engine/n55" },
          { label: "N57", href: "/engine/n57" },
          { label: "N62", href: "/engine/n62" },
          { label: "N62/N63", href: "/engine/n62-n63" },
          { label: "N63", href: "/engine/n63" },
          { label: "N73/N74", href: "/engine/n73-n74" },
        ],
      },
      {
        title: "M-series (classic)",
        links: [
          { label: "M10", href: "/engine/m10" },
          { label: "M20", href: "/engine/m20" },
          { label: "M21", href: "/engine/m21" },
          { label: "M30", href: "/engine/m30" },
          { label: "M40/M42/M43/M44", href: "/engine/m40-m42-m43-m44" },
          { label: "M47", href: "/engine/m47" },
          { label: "M50/M52/M54", href: "/engine/m50-m52-m54" },
          { label: "M57", href: "/engine/m57" },
          { label: "M60/M62", href: "/engine/m60-m62" },
          { label: "M70/M73", href: "/engine/m70-m73" },
          { label: "M88/S38", href: "/engine/m88-s38" },
        ],
      },
      {
        title: "S-series (M Division)",
        links: [
          { label: "S14", href: "/engine/s14" },
          { label: "S50/S52/S54", href: "/engine/s50-s52-s54" },
          { label: "S55", href: "/engine/s55" },
          { label: "S62", href: "/engine/s62" },
          { label: "S63", href: "/engine/s63" },
          { label: "S63/S65", href: "/engine/s63-s65" },
          { label: "S70/S85", href: "/engine/s70-s85" },
        ],
      },
    ],
    footerLink: { label: "View All Engines →", href: "/engine" },
  },
  {
    id: "problems",
    label: "PROBLEMS & SYMPTOMS",
    kind: "columns",
    groups: [
      {
        title: "Common Failures",
        links: [
          { label: "N47 Timing Chain", href: "/failures/n47-timing-chain" },
          { label: "N54 High Pressure Fuel Pump", href: "/failures/n54-high-pressure-fuel-pump" },
          { label: "N63 Oil Consumption", href: "/failures/n63-oil-consumption" },
          { label: "Rod Bearing Wear (S63)", href: "/failures/rod-bearing-wear-s63" },
          { label: "S55 Crank Hub Failure", href: "/failures/s55-crank-hub-failure" },
          { label: "N20 Timing Chain Tensioner", href: "/failures/n20-timing-chain-tensioner" },
          { label: "Turbocharger Failure", href: "/failures/turbocharger-failure" },
          { label: "DPF Blockage", href: "/failures/dpf-blockage" },
        ],
        viewAll: { label: "View All Failures →", href: "/failures" },
      },
      {
        title: "Symptoms",
        links: [
          { label: "Black Smoke", href: "/symptoms/black-smoke" },
          { label: "Blue Smoke", href: "/symptoms/blue-smoke" },
          { label: "White Smoke", href: "/symptoms/white-smoke" },
          { label: "Cold Start Rattle", href: "/symptoms/cold-start-rattle" },
          { label: "Engine Overheating", href: "/symptoms/engine-overheating" },
          { label: "Limp Mode", href: "/symptoms/limp-mode" },
          { label: "Excessive Oil Consumption", href: "/symptoms/excessive-oil-consumption" },
          { label: "Won't Start", href: "/symptoms/wont-start" },
        ],
        viewAll: { label: "View All Symptoms →", href: "/symptoms" },
      },
      {
        title: "Warning Lights",
        links: [
          { label: "Engine Management Light", href: "/warning-lights/engine-management-light" },
          { label: "Oil Pressure Warning", href: "/warning-lights/oil-pressure-warning" },
          { label: "DPF Warning Light", href: "/warning-lights/dpf-warning-light" },
          { label: "Coolant Temperature Warning", href: "/warning-lights/coolant-temperature-warning" },
          { label: "AdBlue Warning", href: "/warning-lights/adblue-warning" },
          { label: "Limp Home Mode", href: "/warning-lights/limp-home-mode" },
          { label: "Glow Plug Light", href: "/warning-lights/glow-plug-light" },
          { label: "Battery Warning", href: "/warning-lights/battery-warning" },
        ],
        viewAll: { label: "View All (10) →", href: "/warning-lights" },
      },
      {
        title: "Fault Codes",
        links: [
          { label: "P0300", href: "/fault-codes/p0300" },
          { label: "P0016", href: "/fault-codes/p0016" },
          { label: "P0011", href: "/fault-codes/p0011" },
          { label: "P0299", href: "/fault-codes/p0299" },
          { label: "P0087", href: "/fault-codes/p0087" },
          { label: "P0401", href: "/fault-codes/p0401" },
          { label: "P0420", href: "/fault-codes/p0420" },
          { label: "P2463", href: "/fault-codes/p2463" },
        ],
        viewAll: { label: "View All Fault Codes →", href: "/fault-codes" },
      },
    ],
  },
  {
    id: "guides",
    label: "GUIDES",
    kind: "columns",
    groups: [
      {
        title: "Buying & Ranking",
        links: [
          { label: "BMW Engines Ranked Worst to Best", href: "/blog/bmw-engines-ranked-worst-to-best" },
          { label: "Best BMW Diesel Engines", href: "/blog/best-bmw-diesel-engines" },
          { label: "Best BMW Petrol Engines", href: "/blog/best-bmw-petrol-engines" },
          { label: "Most Reliable BMW Engine", href: "/blog/most-reliable-bmw-engine" },
          { label: "BMW Engines to Avoid", href: "/blog/bmw-engines-to-avoid" },
          { label: "Best BMW 3 Series Engines", href: "/blog/best-bmw-3-series-engines" },
        ],
      },
      {
        title: "Ownership",
        links: [
          { label: "How Long Do BMW Diesel Engines Last", href: "/blog/how-long-do-bmw-diesel-engines-last" },
          { label: "High Mileage BMW Maintenance Schedule", href: "/blog/high-mileage-bmw-maintenance-schedule" },
          { label: "Cheapest BMW to Maintain", href: "/blog/cheapest-bmw-to-maintain" },
          { label: "Best BMW for High Mileage", href: "/blog/best-bmw-for-high-mileage" },
          { label: "BMW Engine Lifespan by Generation", href: "/blog/bmw-engine-lifespan-by-generation" },
        ],
      },
      {
        title: "Problems Explained",
        links: [
          { label: "N47 Timing Chain Failure Timeline", href: "/blog/n47-timing-chain-failure-timeline" },
          { label: "N54 HPFP Failure Timeline", href: "/blog/n54-hpfp-failure-timeline" },
          { label: "N63 Oil Consumption Timeline", href: "/blog/n63-oil-consumption-timeline" },
          { label: "Are BMW Diesels Unreliable?", href: "/blog/are-bmw-diesels-unreliable" },
          { label: "Do All N47 Engines Have Timing Chain Problems?", href: "/blog/do-all-n47-engines-have-timing-chain-problems" },
        ],
      },
    ],
    footerLink: { label: "View All Guides →", href: "/blog" },
  },
  {
    id: "resources",
    label: "RESOURCES",
    kind: "columns",
    groups: [
      {
        title: "Compare & Research",
        links: [
          { label: "Compare Models & Engines", href: "/compare" },
          { label: "Fitment Guide", href: "/fitment" },
          { label: "Fitment Matrix", href: "/fitment/matrix" },
          { label: "Technical Library", href: "/technical" },
          { label: "Case Studies", href: "/case-studies" },
          { label: "Recalls", href: "/recalls" },
          { label: "Ownership Economics", href: "/economics" },
        ],
      },
      {
        title: "Tools",
        links: [
          { label: "Repair vs Replace Calculator", href: "/tools/repair-vs-replace-calculator" },
          { label: "Ownership Cost Calculator", href: "/tools/ownership-cost-calculator" },
          { label: "Registration Lookup", href: "/tools/registration-lookup" },
          { label: "VIN Decoder", href: "/tools/vin-decoder" },
          { label: "Oil Finder", href: "/tools/oil-finder" },
          { label: "Engine Compatibility Checker", href: "/tools/engine-compatibility-checker" },
          { label: "Diagnostic Wizard", href: "/tools/diagnostic-wizard" },
          { label: "Engine Value Checker", href: "/tools/engine-value-checker" },
        ],
      },
      {
        title: "Data & Reports",
        links: [
          { label: "Research Centre", href: "/data" },
          { label: "Reliability Index 2026", href: "/data/engine-failure-index-2026" },
          { label: "Failure Trends 2026", href: "/data/bmw-failure-trends-2026" },
          { label: "Cost Index 2026", href: "/data/bmw-cost-index-2026" },
          { label: "Most Reliable by Year", href: "/data/most-reliable-bmw-engines-by-year" },
          { label: "Methodology", href: "/data/methodology" },
          { label: "Failure Rate by Engine", href: "/data/failure-rate-by-engine" },
        ],
      },
    ],
    footerLink: { label: "All Tools →", href: "/tools" },
  },
  {
    id: "blog",
    label: "BLOG",
    kind: "link",
    href: "/blog",
  },
];
